### ISSUE TITLE
cdlbelthold issue

### ISSUE THREAD

**Issue by viotemp1** [Yvictor/polars_ta_extension#16]
Hi,
I tried this code:
```
pl_dataframe = pl.from_pandas(dataframe)
plta.cdlbelthold(pl_dataframe)
```
and is giving me this error:
```
-> 5231     return open.ta.cdlbelthold(high, low, close)
AttributeError: 'DataFrame' object has no attribute 'ta'
```

I checked pl_dataframe["open"] and it is a polar series: polars.series.series.Series
I installed polars-talib in a new conda env with pip install polars-lts-cpu polars-talib.
Using python talib (TA-Lib), the pattern function works fine 
```
ta.CDLBELTHOLD(dataframe)
0        0
1        0
2        0
3        0
4        0
      ... 
```
What could be wrong?

**Comment by Yvictor** [comment]
It looks like you’re trying to pass a Polars DataFrame to plta.cdlbelthold, but plta.cdlbelthold is actually a Polars expression, so it expects a Polars expression, not a DataFrame. Check the README in the [polars_ta_extension](https://github.com/Yvictor/polars_ta_extension/blob/master/README.md) for examples on the correct usage. Please review the documentation before opening an issue to avoid misunderstandings!
