### ISSUE TITLE
private fields in talib crate kwargs structs / missing "new" method

### ISSUE THREAD

**Issue by bionicles** [Yvictor/polars_ta_extension#19]
Hi Yvictor,

Great idea for a project!

Could you please add "new" methods to build the kwarg structs? i wanted to use the talib crate but it won't compile because I can't build the required kwargs struct from another crate

example of the problem:

can't construct the SarKwargs struct:
![image](https://github.com/user-attachments/assets/d0e54b95-2855-42fc-93aa-0494ccd2d23b)

no "new" method to build the struct:
![image](https://github.com/user-attachments/assets/f7db0c32-6b59-494c-a3a5-1247a389953f)

Benefit to fix: others could use the rust crate and help maintain it

**Comment by Yvictor** [comment]
With builder pattern support in version 0.1.2
