### ISSUE TITLE
ta-lib-python is supposed to already natively support polars dataframes?

### ISSUE THREAD

**Issue by Franky1** [Yvictor/polars_ta_extension#2]
ta-lib-python is supposed to already natively support polars dataframes?
<https://github.com/TA-Lib/ta-lib-python/issues/471>

Just out of interest: What is the difference to this library?

**Comment by Yvictor** [comment]
It supports native Polars expressions, offering the same advantages as default expressions: optimization, parallelism, and native Rust performance.
You can find more information in this link https://docs.pola.rs/user-guide/expressions/plugins/

 
One particularly handy usage example involves chaining with native Polars expressions like `over` to partition and parallelize calculations for different symbols, as demonstrated below:
```
df.with_columns(
    pl.col("close").ta.ema(5).over("symbol").alias("ema5"),
    pl.col("close").ta.macd(12, 26, 9).over("symbol").struct.field("macd"),
)
```
With ta-lib-python, you will be blocked by the Python Global Interpreter Lock (GIL), so you can't run this in parallel.
