### ISSUE TITLE
Failed to install on rust

### ISSUE THREAD

**Issue by piotryordanov** [Yvictor/polars_ta_extension#3]
So, in my project I did `cargo add talib-sys`
The build fails with this error:
```sh
   Compiling talib-sys v0.1.0
error: could not find native static library `ta_lib`, perhaps an -L flag is missing?

error: could not compile `talib-sys` (lib) due to 1 previous error
```

I figured that the solution is to find out the location. In my case:
`~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/talib-sys-0.1.0`

Then, i cloned this repo into `/tmp`, built it myself and did:
`cp /tmp/polars_ta_extension/talib-sys/dependencies ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/talib-sys-0.1.0`

That allowed me to build properly.
Maybe the cargo version is not up to date?

**Comment by Yvictor** [comment]
In my env
I just try to reproduce with below scripts
``` bash
cargo new rust_talib_test
cd rust_talib_test
cargo add talib-sys
cargo run
```
but without any issue 
Maybe need to check you can build talib in your env?
i think the root cause will ta-lib c build env not prepared
