### ISSUE TITLE
DeprecationWarning: `register_plugin` is deprecated. Use `polars.plugins.register_plugin_function` instead.

### ISSUE THREAD

**Issue by ctyler9** [Yvictor/polars_ta_extension#4]
Just a warning I got. May dig into and make PR myself but just making note

**Comment by yarimiz** [comment]
Did you have a chance looking at it? I'm facing it now while using polars 1.2.1 and thinking about implementing the PR myself, but my knowledge is the plugins areas of polars is minimal

**Comment by yarimiz** [comment]
@Yvictor @ctyler9 i created https://github.com/Yvictor/polars_ta_extension/pull/10 to start handling the issue.

**Comment by Yvictor** [comment]
fix with version 0.1.3
