### ISSUE TITLE
Request for ARM-compatible wheels for M1 Macs

### ISSUE THREAD

**Issue by 0xAndrii** [Yvictor/polars_ta_extension#5]
### Environment

- **Operating System**: macOS (Apple M1)
- **Python Version**: Python 3.12.3
- **pip Version**: pip 24.0

### Description

I am trying to install `polars-talib==0.1.2` on my M1 Mac but am encountering an error indicating that there are no matching distributions found. This suggests that there might not be pre-built wheels available for ARM architecture. 

### Steps to Reproduce

1. Run `pip install polars-talib==0.1.2`
2. Encounter error messages indicating incompatibility.

`× No solution found when resolving dependencies:
  ╰─▶ Because polars-talib==0.1.2 is unusable because no wheels are available with a matching Python implementation and you require polars-talib==0.1.2, we can conclude that the requirements are unsatisfiable.`

### Possible Solution

It would be highly beneficial for Mac users with ARM architecture if ARM-compatible wheels could be made available.

### Additional Context

Really appreciate your help in making this library accessible on different architectures.

**Comment by Yvictor** [comment]
support it

**Comment by 0xAndrii** [comment]
Thank you so much for your prompt support on this issue @Yvictor! 

I would like to request an additional feature: support for the manylinux aarch64.whl as well. 
This would be incredibly helpful for testing the library in Docker environments.

Thanks again for your assistance!
